[build]
  command = "gatsby build"
  publish = "public/"

[build.environment]
NODE_VERSION="12.22.3"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "/"
  to = "/work"
  status = 301
  force = false